import {
  Bath,
  AirVent,
  Baby,
  Bed,
  BedDouble,
  Binoculars,
  Bike,
  Bubbles,
  Car,
  CarFront,
  Caravan,
  CheckCircle,
  Cigarette,
  CigaretteOff,
  Clock,
  CloudRain,
  Coffee,
  CookingPot,
  Cross,
  Droplets,
  Dumbbell,
  Fan,
  Flame,
  Flower2,
  Heater,
  Heart,
  House,
  HouseWifi,
  Lamp,
  Laptop,
  Leaf,
  Lightbulb,
  Microwave,
  Music,
  Navigation,
  ParkingMeter,
  PartyPopper,
  Projector,
  Refrigerator,
  Ship,
  ShipWheel,
  Sprout,
  Sun,
  Sunset,
  MapPin,
  Mountain,
  PawPrint,
  Shield,
  Star,
  Tent,
  TentTree,
  ThermometerSun,
  Toilet,
  Tv,
  Umbrella,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  WashingMachine,
  Waves,
  Wifi,
  Wind,
  Zap,
} from 'lucide-react';

export const AMENITY_ICON_MAP: Record<string, any> = {
  ac: Wind,
  air_vent: AirVent,
  baby: Baby,
  bath: Bath,
  bathroom: Bath,
  bed: Bed,
  bed_double: BedDouble,
  binoculars: Binoculars,
  bike: Bike,
  atv: Bike,
  atv_rental: Bike,
  breakfast: Coffee,
  bbq: Flame,
  bbq_package: Flame,
  bbq_package_4_pax: Flame,
  bubbles: Bubbles,
  car: Car,
  car_front: CarFront,
  caravan: Caravan,
  cigarettes: Cigarette,
  cigarette: Cigarette,
  no_smoking: CigaretteOff,
  clock: Clock,
  rain: CloudRain,
  cloud_rain: CloudRain,
  coffee: Coffee,
  fire: Flame,
  first_aid: Cross,
  firepit: Flame,
  fan: Fan,
  fitness: Dumbbell,
  gym: Dumbbell,
  spa: Flower2,
  heater: Heater,
  heart: Heart,
  hot_water: ThermometerSun,
  hot_tub: Waves,
  house: House,
  house_wifi: HouseWifi,
  lamp: Lamp,
  laptop: Laptop,
  leaf: Leaf,
  kitchen: CookingPot,
  light: Lightbulb,
  lightbulb: Lightbulb,
  laundry: WashingMachine,
  washer: WashingMachine,
  microwave: Microwave,
  lake: Waves,
  map_pin: MapPin,
  mountain: Mountain,
  music: Music,
  navigation: Navigation,
  parking_meter: ParkingMeter,
  parking: Car,
  party: PartyPopper,
  pet: PawPrint,
  pool: Waves,
  river: Waves,
  projector: Projector,
  refrigerator: Refrigerator,
  ship: Ship,
  ship_wheel: ShipWheel,
  sprout: Sprout,
  sun: Sun,
  sunset: Sunset,
  tent_tree: TentTree,
  security: Shield,
  shield: Shield,
  shower: Bath,
  shower_water: Droplets,
  star: Star,
  tent: Tent,
  toilet: Toilet,
  tv: Tv,
  umbrella: Umbrella,
  users: Users,
  family: UsersRound,
  utensils: Utensils,
  utensils_crossed: UtensilsCrossed,
  view: Mountain,
  wifi: Wifi,
  zap: Zap,
};

export const AMENITY_ICON_FALLBACK = CheckCircle;
export const AMENITY_ICON_KEYS = Object.keys(AMENITY_ICON_MAP);
